site_name: My MkDocs Material Documentation
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - toc.follow
    - navigation.sections

      
plugins:
  - mkdocs-jupyter

nav:
  - Home: index.md
  - Notebook: test.ipynb
  - 'Probability':
      - Mathematical Probability: probability/probability_math.md
      - Probability Basics: probability_basics.md
  - 'Statistics Basics':
      - Deskriptive Statistik: descriptive.md
      - Verteilungen: distributions.md
      - Schliessende Statistik: inference.md
      - Mathematische Statistik: mathematical_stats.md
      - Offene Fragen: open_questions_stats.md
      - Glossar: glossary_basics.md
  - 'Ökonometrie':
      - Lineare Regression: lin_reg.md
      - Offene Fragen: open_questions_regression.md
  - 'A/B Testing':
      - A/B Testing Übersicht: a_b_testing.md
      - Metriken: metrics.md
      - Experimentdesign: design.md
      - Analysis: analysis.md
      - Offene Fragen: open_questions_AB.md
  - 'Machine Learning':
      - Offene Fragen: open_questions_ML.md
  - 'Offene Fragen':
      - Allgemeine Offene Fragen: openquestions.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
