site_name: My MkDocs Material Documentation
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - toc.follow
    - navigation.sections

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

      
plugins:
  - mkdocs-jupyter
  - mkdocs-pdf

nav:
  - Home: index.md
  - Notebook: test.ipynb
  - 'Probability':
      - Mathematical Probability: probability/probability_math.md
      - Probability Basics: probability_basics.md
  - 'Statistics Basics':
      - Deskriptive Statistik: descriptive.md
      - Verteilungen: distributions.md
      - Schliessende Statistik: inference.md
      - Mathematische Statistik: mathematical_stats.md
      - Offene Fragen: open_questions_stats.md
      - Glossar: glossary_basics.md
  - 'Ökonometrie':
      - Lineare Regression: lin_reg.md
      - Offene Fragen: open_questions_regression.md
  - 'A/B Testing':
      - A/B Testing Übersicht: a_b_testing.md
      - Metriken: metrics.md
      - Experimentdesign: design.md
      - Analysis: analysis.md
      - Offene Fragen: open_questions_AB.md
  - 'Machine Learning':
      - Offene Fragen: open_questions_ML.md
  - 'Offene Fragen':
      - Allgemeine Offene Fragen: openquestions.md
  - 'SSO':
      - Probability Distributions: prob_distributions.md
      - Assessing Normality: assessing_normality.md
      - Summarizing data: summarizing_data.md
      - Sampling distributions: sampling_distributions.md
      - Estimating mean and proportion: estimating.md
      - Hypothesis testing: hypothesis_testing.md
      - Inferences from two samples: two_samples.md
      - Nonparametric tests: nonparametric_tests.md
      - Contingency tables: contingency_tables.md
      - Simple linear regression: linear_regression.md
      - Working with normal distributions: skills_normal_distribution.md
      - Estimating: skills_estimating.md
      - Hypothesis testing: skills_hypothesis_testing.md
      - Inferences Two Samples: skills_two_samples.md
      - Nonparametric Tests: skills_nonparametric_tests.md
      - Contingency Tables: skills_contingency_tables.md
      - Simple linear regression: skills_linear_regression.md
      - (Integer) linear optimization problems: ilo_problems.md
      - Algorithms: algorithms.md
      - Simulation optimization: simulation_optimization.md
      - Exam prep stats: exam_prep_statistics.md
      - Exam prep so: exam_prep_so.md
      - Lecture Questions: lecture_questions.md
      - Questions Contents & Skills: questions_content_skills.md
