site_name: My MkDocs Material Documentation
site_url: https://sitename.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - toc.follow
    - navigation.sections

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

      
plugins:
  - mkdocs-jupyter
  - mkdocs-pdf

nav:
  - Home: index.md
  - Notebook: test.ipynb
  - 'Probability':
      - Mathematical Probability: probability/probability_math.md
      - Probability Basics: probability_basics.md
  - 'Statistics Basics':
      - Deskriptive Statistik: descriptive.md
      - Verteilungen: distributions.md
      - Schliessende Statistik: inference.md
      - Mathematische Statistik: mathematical_stats.md
      - Offene Fragen: open_questions_stats.md
      - Glossar: glossary_basics.md
  - 'Ökonometrie':
      - Lineare Regression: lin_reg.md
      - Offene Fragen: open_questions_regression.md
  - 'A/B Testing':
      - A/B Testing Übersicht: a_b_testing.md
      - Metriken: metrics.md
      - Experimentdesign: design.md
      - Analysis: analysis.md
      - Offene Fragen: open_questions_AB.md
  - 'Machine Learning':
      - Offene Fragen: open_questions_ML.md
  - 'Offene Fragen':
      - Allgemeine Offene Fragen: openquestions.md
  - 'SSO':
      - Working with normal distributions: sso/skills_normal_distribution.md
      - Estimating: sso/skills_estimating.md
      - Hypothesis testing: sso/skills_hypothesis_testing.md
      - Inferences Two Samples: sso/skills_two_samples.md
      - Nonparametric Tests: sso/skills_nonparametric_tests.md
      - Contingency Tables: sso/skills_contingency_tables.md
      - Simple linear regression: sso/skills_linear_regression.md
      - (Integer) linear optimization problems: sso/ilo_problems.md
      - Exam prep stats: sso/exam_prep_statistics.md
      - Exam prep so: sso/exam_prep_so.md
      - Questions Contents & Skills: sso/questions_content_skills.md
  - 'AFCS':
      - Cheatsheet R: afcs/cheatsheet_r.md
      - Ch. 1 Intro: afcs/intro.md
      - Ch. 2 Time Series Graphics: afcs/ts_graphics.md
      - Ch. 3 Time Series Decomposition: afcs/ts_decomp.md
      - Ch. 4 Features: afcs/features.md
      - Ch. 5 Forecasting Toolbox: afcs/forecast_toolbox.md
      - Ch. 7 Time Series Regregression models: afcs/regression.md
      - Ch. 8 Exponential Smoothing: afcs/smoothing.md
      - Ch. 9 ARIMA models: afcs/arima.md
      - Ch. 10 Dynamic regression models: afcs/dynamic_reg_models.md
      - Ch. 11 Hierarchical and grouped time series: afcs/hierarchical.md
  - 'Fundamentals':
      - Cheat Sheet Numpy: fundamentals/numpy.md
      - Cheat Sheet Pandas: fundamentals/pandas.md
      - Questions Literature: fundamentals/questions_literature.md
      - Part 1 - Life-cycle, EDA, Tools: fundamentals/part1_eda.md
      - Part 2 - Data Visualization: fundamentals/part2_data_visualization.md
      - Part 3 - Supervised Learning: fundamentals/part3_supervised_learning.md
      - Part 4 - Unsupervised Learning: fundamentals/part4_unsupervised_learning.md
      - Part 5 - Ethics: fundamentals/part5_ethics.md
